spring:
  main:
    allow-bean-definition-overriding: true
  config:
    import: classpath:logbook.yml
  application:
    name: rikser-yandex-fetcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_URL}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      schema: rikser-yandex-fetcher
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS "rikser-yandex-fetcher"
      maximum-pool-size: 5
      connection-timeout: 5000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    default-schema: rikser-yandex-fetcher
    liquibase-schema: rikser-yandex-fetcher
    drop-first: false
  cloud:
    compatibility-verifier:
      enabled: false
  data:
    redis:
      host: ${REDIS_URL}
      port: 6379
      password: ${REDIS_PASSWORD}
      timeout: 2000ms

server:
  port: 8081

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

bundle:
  security:
    enabled: true
    service:
      enabled: true
      url: http://security:8081
  redis:
    TTL: P1D
    prefix: yandex-query
    enabled: true
  kafka:
    enabled: true
    user: ${KAFKA_USER}
    password: ${KAFKA_PASSWORD}
    kafkaUrl: ${KAFKA_URL}


management:
  tracing:
    enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
    health:
      show-details: always
      status:
        http-mapping:
          down: 503

yandex:
  token: ${YANDEX_TOKEN}
  searchApiUrl: ${YANDEX_SEARCH_API_URL}
  operationApiUrl: ${YANDEX_OPERATION_API_URL}
  spellerApi: ${YANDEX_SPELLER_API_URL}
  maxAttempts: 4
  delay: 500

kafka:
  max-fetch-limit: 200
  scheduler-delay: PT10S