spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  application:
    name: rikser-yandex-fetcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_URL}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      schema: rikser-yandex-fetcher
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS "rikser-yandex-fetcher"
      maximum-pool-size: 5
      connection-timeout: 5000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    default-schema: rikser-yandex-fetcher
    liquibase-schema: rikser-yandex-fetcher
    drop-first: false
  cloud:
    compatibility-verifier:
      enabled: false
  http:
    codecs:
      max-in-memory-size: 10MB
  webflux:
    client:
      log-request-details: true

server:
  port: 8081

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

security:
  enabled: true
  service:
    enabled: true
    url: http://security:8081


management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    endpoint:
      loggers:
        enabled: true
    health:
      show-details: always
      status:
        http-mapping:
          down: 503
