spring:
  config:
    import: classpath:logbook.yml
  main:
    allow-bean-definition-overriding: true
  application:
    name: rikser-yandex-fetcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_URL}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      schema: rikser-yandex-fetcher
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS "rikser-yandex-fetcher"
      maximum-pool-size: 5
      connection-timeout: 5000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    default-schema: rikser-yandex-fetcher
    liquibase-schema: rikser-yandex-fetcher
    drop-first: false
  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: 8081

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

bundle:
  security:
    enabled: true
    service:
      enabled: true
      url: http://security:8081


management:
  tracing:
    enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
    health:
      show-details: always
      status:
        http-mapping:
          down: 503