spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: rikser-yandex-fetcher
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    drop-first: true
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    hikari:
      schema: public

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

bundle:
  security:
    enabled: false
    service:
      enabled: false
      url: http://localhost:8081
  redis:
    enabled: false
  kafka:
    enabled: false
    kafka-url: http://localhost:9092
    user: user
    password: password

logbook:
  enabled: false

yandex:
  token: token
  search-api-url: http://localhost:8081
  operation-api-url: http://localhost:8081
  speller-api: http://localhost:8081
  max-attempts: 4
  delay: 500
  exclude-domains: vk.com,pikabu.ru,rutube.ru,youtube.com,yandex.ru,mail.ru
  pool-size: 100
  queue-size: 100
  scheduler-delay: PT10S

kafka:
  max-fetch-limit: 200

schedulers:
  kafka:
    delay: PT10S
