spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: rikser-yandex-fetcher
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    drop-first: true
  cloud:
    compatibility-verifier:
      enabled: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false


yandex:
  token: token
  searchApiUrl: http://localhost:8081
  operationApiUrl: http://localhost:8081
  maxAttempts: 4
  delay: 500